-- Seeds the current hardcoded menu into the new menu_items table.
-- Generated programmatically from src/lib/menu-data.ts (not hand-typed) to
-- avoid transcription mistakes across every row's price.
insert into menu_items (id, name, price, category, color, image, available, sort_order)
values
  ('coffee-iced-americano', 'Iced Americano', 145, 'Coffee', '#5C3A1E', '/americano.png', true, 0),
  ('coffee-iced-cafe-latte', 'Iced Cafe Latte', 150, 'Coffee', '#9C6B3E', '/cafe-latte.png', true, 10),
  ('coffee-einspanner', 'Einspänner', 155, 'Coffee', '#3B2314', '/einspanner.png', true, 20),
  ('coffee-iced-cappuccino', 'Iced Cappuccino', 150, 'Coffee', '#B4793A', '/cappucino.png', true, 30),
  ('coffee-iced-spanish-latte', 'Iced Spanish Latte', 160, 'Coffee', '#A9754A', '/spanish-latte.png', true, 40),
  ('coffee-iced-vanilla-latte', 'Iced Vanilla Latte', 165, 'Coffee', '#C99A4B', '/vanilla-latte.png', true, 50),
  ('coffee-iced-sea-salt-latte', 'Iced Sea Salt Latte', 165, 'Coffee', '#B8AFA3', '/sea-salt-latte.png', true, 60),
  ('coffee-iced-hazelnut-latte', 'Iced Hazelnut Latte', 165, 'Coffee', '#8A5A34', '/hazelnut-latte.png', true, 70),
  ('coffee-cream-latte', 'Cream Latte', 165, 'Coffee', '#D9BE95', '/cream-latte.png', true, 80),
  ('coffee-iced-cafe-mocha', 'Iced Cafe Mocha', 170, 'Coffee', '#6B4226', '/cafe-mocha.png', true, 90),
  ('coffee-iced-caramel-macchiato', 'Iced Caramel Macchiato', 175, 'Coffee', '#C08A3E', '/caramel-macchiato.png', true, 100),
  ('coffee-iced-butterscotch-latte', 'Iced Butterscotch Latte', 175, 'Coffee', '#B4793A', '/butterscotch-latte.png', true, 110),
  ('coffee-iced-toffee-nut-latte', 'Iced Toffee Nut Latte', 180, 'Coffee', '#8A5A34', '/toffee-nut-latte.png', true, 120),
  ('coffee-iced-chestnut-latte', 'Iced Chestnut Latte', 185, 'Coffee', '#9C6B3E', '/chestnut-latte.png', true, 130),
  ('coffee-iced-dirty-matcha', 'Iced Dirty Matcha', 180, 'Coffee', '#7FA35C', '/dirty-matcha.png', true, 140),
  ('coffee-iced-white-chocolate-mocha', 'Iced White Chocolate Mocha', 180, 'Coffee', '#E8D9B5', '/white-chocolate-mocha.png', true, 150),
  ('coffee-ube-dusk', 'Ube Dusk', 190, 'Coffee', '#8E7BC4', '/ube-dusk.png', true, 160),
  ('coffee-strawpresso-latte', 'Strawpresso Latte', 195, 'Coffee', '#E24E5A', '/strawpresso.png', true, 170),
  ('coffee-cold-brew', 'Cold Brew', 180, 'Coffee', '#3B2314', '/cold-brew.png', true, 180),
  ('coffee-cold-brew-latte', 'Cold Brew Latte', 190, 'Coffee', '#9C6B3E', '/cold-brew-latte.png', true, 190),
  ('coffee-caramel-cold-brew', 'Caramel Cold Brew', 200, 'Coffee', '#C08A3E', '/caramel-cold-brew.png', true, 200),
  ('hot-drinks-hot-americano', 'Hot Americano', 125, 'Hot Drinks', '#5C3A1E', '/hot-coffee.png', true, 0),
  ('hot-drinks-hot-cafe-latte', 'Hot Cafe Latte', 145, 'Hot Drinks', '#9C6B3E', '/hot-coffee.png', true, 10),
  ('hot-drinks-hot-cappuccino', 'Hot Cappuccino', 145, 'Hot Drinks', '#B4793A', '/hot-coffee.png', true, 20),
  ('hot-drinks-hot-spanish-latte', 'Hot Spanish Latte', 150, 'Hot Drinks', '#A9754A', '/hot-coffee.png', true, 30),
  ('hot-drinks-hot-vanilla-latte', 'Hot Vanilla Latte', 155, 'Hot Drinks', '#C99A4B', '/hot-coffee.png', true, 40),
  ('hot-drinks-hot-sea-salt-latte', 'Hot Sea Salt Latte', 155, 'Hot Drinks', '#B8AFA3', '/hot-coffee.png', true, 50),
  ('hot-drinks-hot-hazelnut-latte', 'Hot Hazelnut Latte', 155, 'Hot Drinks', '#8A5A34', '/hot-coffee.png', true, 60),
  ('hot-drinks-hot-cafe-mocha', 'Hot Cafe Mocha', 160, 'Hot Drinks', '#6B4226', '/hot-coffee.png', true, 70),
  ('hot-drinks-hot-caramel-macchiato', 'Hot Caramel Macchiato', 165, 'Hot Drinks', '#C08A3E', '/hot-coffee.png', true, 80),
  ('hot-drinks-hot-butterscotch', 'Hot Butterscotch', 165, 'Hot Drinks', '#B4793A', '/hot-coffee.png', true, 90),
  ('hot-drinks-hot-dirty-matcha', 'Hot Dirty Matcha', 175, 'Hot Drinks', '#7FA35C', '/hot-coffee.png', true, 100),
  ('hot-drinks-hot-white-chocolate-mocha', 'Hot White Chocolate Mocha', 175, 'Hot Drinks', '#E8D9B5', '/hot-coffee.png', true, 110),
  ('hot-drinks-hot-green-tea', 'Hot Green Tea', 120, 'Hot Drinks', '#7FA35C', '/hot-coffee.png', true, 120),
  ('hot-drinks-hot-jasmine-tea', 'Hot Jasmine Tea', 120, 'Hot Drinks', '#D9D08A', '/hot-coffee.png', true, 130),
  ('hot-drinks-hot-lemon-tea', 'Hot Lemon Tea', 120, 'Hot Drinks', '#F2B705', '/hot-coffee.png', true, 140),
  ('hot-drinks-hot-matcha-latte', 'Hot Matcha Latte', 165, 'Hot Drinks', '#7FA35C', '/hot-coffee.png', true, 150),
  ('hot-drinks-hot-chocolate-latte', 'Hot Chocolate Latte', 155, 'Hot Drinks', '#6B4226', '/hot-coffee.png', true, 160),
  ('signature-drinks-lemon-ade', 'Lemon Ade', 160, 'Signature Drinks', '#F2B705', '/lemon-ade.png', true, 0),
  ('signature-drinks-retro-coffee', 'Retro Coffee', 190, 'Signature Drinks', '#B4793A', '/retro-coffee.png', true, 10),
  ('signature-drinks-coconut-matcha-cloud', 'Coconut Matcha Cloud', 185, 'Signature Drinks', '#A9C46F', '/coconut-matcha-cloud.png', true, 20),
  ('signature-drinks-jolly-pong', 'Jolly Pong', 195, 'Signature Drinks', '#C99A4B', '/jolly-pong.png', true, 30),
  ('signature-drinks-mint-chocolate', 'Mint Chocolate', 195, 'Signature Drinks', '#5FBF8F', '/mint-chocolate.png', true, 40),
  ('signature-drinks-cube-latte', 'Cube Latte', 185, 'Signature Drinks', '#8A5A34', '/cube-latte.png', true, 50),
  ('non-coffee-matcha-berry-latte', 'Matcha Berry Latte', 190, 'Non Coffee', '#B15C7A', '/matchaberry-latte.png', true, 0),
  ('non-coffee-chocolate-latte', 'Chocolate Latte', 165, 'Non Coffee', '#6B4226', '/chocolate-latte.png', true, 10),
  ('non-coffee-misugaru', 'Misugaru', 150, 'Non Coffee', '#C9A66B', '/misugaru.png', true, 20),
  ('non-coffee-coconut-matcha-latte', 'Coconut Matcha Latte', 185, 'Non Coffee', '#A9C46F', '/coconut-matcha-latte.png', true, 30),
  ('non-coffee-ube-coconut-latte', 'Ube Coconut Latte', 175, 'Non Coffee', '#8E7BC4', '/ube-coconut-latte.png', true, 40),
  ('non-coffee-ube-latte', 'Ube Latte', 165, 'Non Coffee', '#8E7BC4', '/ube-latte.png', true, 50),
  ('non-coffee-moonlight-matcha', 'Moonlight Matcha', 195, 'Non Coffee', '#7FA35C', '/moonlight-matcha.png', true, 60),
  ('non-coffee-shikye', 'Shikye', 155, 'Non Coffee', '#D9BE95', '/shikye.png', true, 70),
  ('non-coffee-matcha-latte', 'Matcha Latte', 180, 'Non Coffee', '#7FA35C', '/matcha-latte.png', true, 80),
  ('frappuccino-matcha-frappe', 'Matcha Frappe', 205, 'Frappuccino', '#7FA35C', '/matcha-frappe.png', true, 0),
  ('frappuccino-cookies-n-cream-frappe', 'Cookies N Cream Frappe', 200, 'Frappuccino', '#B8AFA3', '/cookies-and-cream.png', true, 10),
  ('frappuccino-java-chip', 'Java Chip', 210, 'Frappuccino', '#6B4226', '/java-chip.png', true, 20),
  ('frappuccino-strawberry-frappe', 'Strawberry Frappe', 200, 'Frappuccino', '#E24E5A', '/strawberry.png', true, 30),
  ('frappuccino-vanilla-coffee-frappe', 'Vanilla Coffee Frappe', 185, 'Frappuccino', '#C99A4B', '/vanilla-coffee.png', true, 40),
  ('frappuccino-biscoff-frappe', 'Biscoff Frappe', 200, 'Frappuccino', '#B4793A', '/biscoff.png', true, 50),
  ('frappuccino-ube-cream', 'Ube Cream', 190, 'Frappuccino', '#8E7BC4', '/ube-cream.png', true, 60),
  ('frappuccino-strawberry-banana', 'Strawberry Banana', 210, 'Frappuccino', '#F2B705', '/strawberry-banana-milk.png', true, 70),
  ('frappuccino-jolly-pong', 'Jolly Pong', 195, 'Frappuccino', '#C99A4B', '/jolly-pong.png', true, 80),
  ('frappuccino-mint-chocolate', 'Mint Chocolate', 205, 'Frappuccino', '#5FBF8F', '/mint-chocolate.png', true, 90),
  ('smoothie-strawberry-yogurt', 'Strawberry Yogurt', 195, 'Smoothie', '#E24E5A', '/strawberry-yogurt.png', true, 0),
  ('smoothie-blueberry-yogurt', 'Blueberry Yogurt', 190, 'Smoothie', '#5B6EC9', '/blueberry-yogurt.png', true, 10),
  ('smoothie-plain-yogurt', 'Plain Yogurt', 180, 'Smoothie', '#F4E4C6', '/pure-yogurt.png', true, 20),
  ('smoothie-pure-mango', 'Pure Mango', 185, 'Smoothie', '#F2B705', '/pure-mango.png', true, 30),
  ('refreshers-pomelo-ade', 'Pomelo Ade', 140, 'Refreshers', '#F2B705', '/pomelo-ade.png', true, 0),
  ('refreshers-calamansi-ade', 'Calamansi Ade', 155, 'Refreshers', '#C9D98A', '/calamansi-ade.png', true, 10),
  ('desserts-mellow-cookies-oreo', 'Mellow Cookies Oreo', 165, 'Desserts', '#3B2314', '/mellow-cookies-oreo.png', true, 0),
  ('desserts-dubai-chewy-cookie-bites', 'Dubai Chewy Cookie Bites', 215, 'Desserts', '#6B4226', '/dubai-chewy-cookie-bites.png', true, 10),
  ('desserts-dubai-chewy-cookie', 'Dubai Chewy Cookie', 170, 'Desserts', '#C99A4B', '/dubai-chewy-cookie.png', true, 20),
  ('desserts-choco-chip-muffin', 'Choco Chip Muffin', 125, 'Desserts', '#6B4226', '/choco-chip-muffin.png', true, 30),
  ('desserts-oreo-mini-cheesecake', 'Oreo Mini Cheesecake', 175, 'Desserts', '#F4E4C6', '/oreo-mini-cheesecake.png', true, 40),
  ('desserts-nutella-cheesecake', 'Nutella Cheesecake', 225, 'Desserts', '#8A5A34', '/nutella-cheesecake.png', true, 50),
  ('desserts-chocolate-crinkles', 'Chocolate Crinkles', 95, 'Desserts', '#3B2314', '/crinkles.png', true, 60),
  ('croffle-cookies-n-cream-croffle', 'Cookies N'' Cream Croffle', 165, 'Croffle', '#B8AFA3', '/cookies-n-cream-croffle-1.png', true, 0),
  ('croffle-biscoff-croffle', 'Biscoff Croffle', 175, 'Croffle', '#B4793A', '/biscoff-croffle.png', true, 10),
  ('croffle-strawberry-croffle', 'Strawberry Croffle', 185, 'Croffle', '#E24E5A', '/strawberry-croffle-1.png', true, 20),
  ('mellow-fries-mellow-fries', 'Mellow Fries', 120, 'Mellow Fries', '#C99A4B', '/mellow-fries.png', true, 0),
  ('mini-bungeoppang-mini-bungeoppang', 'Mini Bungeoppang', 145, 'Mini Bungeoppang', '#C9A66B', '/mini-bungeoppang.png', true, 0)
on conflict (id) do nothing;
